#--------------------------------------------------------------------------------------------------
# Default skeleton
#--------------------------------------------------------------------------------------------------


###
### Base image
###
FROM devilbox/php-fpm:8.0-work


###
### Will be populated by Makefile call (e.g. linux/amd64 or linux/arm64)
###
ARG ARCH


###
### Labels
###
# https://github.com/opencontainers/image-spec/blob/master/annotations.md
# The following commented labels will be auto-created by the Makefile command.
#LABEL "org.opencontainers.image.created"=""
#LABEL "org.opencontainers.image.version"=""
#LABEL "org.opencontainers.image.revision"=""
LABEL "maintainer"="Billy Bouman <billybouman@ziggo.nl>"
LABEL "org.opencontainers.image.authors"="cytopia <cytopia@everythingcli.org>"
LABEL "org.opencontainers.image.url"="https://github.com/devilbox/docker-php-fpm-community"
LABEL "org.opencontainers.image.documentation"="https://github.com/devilbox/docker-php-fpm-community"
LABEL "org.opencontainers.image.source"="https://github.com/devilbox/docker-php-fpm-community"
LABEL "org.opencontainers.image.vendor"="devilbox"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.ref.name"="8.0-community"
LABEL "org.opencontainers.image.title"="PHP-FPM 5-community"
LABEL "org.opencontainers.image.description"="PHP-FPM 8.0-community"


#--------------------------------------------------------------------------------------------------
# START OF CUSTOM CODE
#--------------------------------------------------------------------------------------------------

RUN set -eux \
	&& true

USER devilbox
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --skip-chsh --unattended --keep-zshrc \
	&& git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-/home/devilbox/.oh-my-zsh/custom}/themes/powerlevel10k \
	&& git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-/home/devilbox/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
	&& git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-/home/devilbox/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
	&& git clone https://github.com/TamCore/autoupdate-oh-my-zsh-plugins ${ZSH_CUSTOM:-/home/devilbox/.oh-my-zsh/custom}/plugins/autoupdate
USER root

# Files with '.' won't be copied
COPY ./data/zshrc ./data/p10k.zsh ./data/gitstatusd-linux-x86_64 /home/devilbox/

RUN mv /home/devilbox/zshrc /home/devilbox/.zshrc \
	&& mv /home/devilbox/p10k.zsh /home/devilbox/.p10k.zsh
RUN mkdir -p /home/devilbox/.cache/gitstatus \
	&& mv /home/devilbox/gitstatusd-linux-x86_64 /home/devilbox/.cache/gitstatus/gitstatusd-linux-x86_64
RUN chown devilbox:devilbox /home/devilbox/.zshrc \
	&& chown devilbox:devilbox /home/devilbox/.p10k.zsh \
	&& chown devilbox:devilbox /home/devilbox/.cache/gitstatus/gitstatusd-linux-x86_64

#--------------------------------------------------------------------------------------------------
# END OF CUSTOM CODE
#--------------------------------------------------------------------------------------------------


###
### Default upstream volumes
###
VOLUME /shared/backups
VOLUME /var/log/php
VOLUME /var/mail


###
### Default upstream ports
###
EXPOSE 9000


###
### Default upstream workdir
###
WORKDIR /shared/httpd


###
### Default upstream Entrypoint
###
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
ENTRYPOINT ["/docker-entrypoint.sh"]
