---

# filename: devilbox-docker-php-fpm-personal_action.yml
# job-name: devilbox-docker-php-fpm-personal_build
#

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: devilbox-docker-php-fpm-personal_build


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Push or pull_request will be determined in jobs.configure.enabled
  push:
    paths:
      - '.github/workflows/devilbox-docker-php-fpm-personal*.yml'
      - '!.github/workflows/devilbox-docker-php-fpm-personal_schedule.yml'
      - 'Dockerfiles/devilbox-docker-php-fpm-personal/**'
      - '!Dockerfiles/devilbox-docker-php-fpm-personal/*.md'
      - 'tests/**'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/devilbox-docker-php-fpm-personal*.yml'
      - '!.github/workflows/devilbox-docker-php-fpm-personal_schedule.yml'
      - 'Dockerfiles/devilbox-docker-php-fpm-personal/**'
      - '!Dockerfiles/devilbox-docker-php-fpm-personal/*.md'
      - 'tests/**'
      - 'Makefile'
  # Dispatch: allows for manual trigger via GH UI
  workflow_dispatch:


jobs:

  # (1/2) Determine repository params
  params:
    uses: ./.github/workflows/devilbox-docker-php-fpm-personal_params.yml

  # (2/2) Build
  docker:
    needs: [params]
    uses: devilbox/github-actions/.github/workflows/docker-name-version-flavour-arch.yml@master
    with:
      enabled: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && (github.event.pull_request.user.login != 'cytopia')) }}
      can_deploy: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release-') }}
      matrix: ${{ needs.params.outputs.matrix }}
      refs: ${{ needs.params.outputs.refs }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
