name: devilbox-docker-php-fpm-personal_build_and_push

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *" # Runs nightly at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./Dockerfiles/devilbox-docker-php-fpm-personal
          file: ./Dockerfiles/devilbox-docker-php-fpm-personal/Dockerfile-${{ matrix.versions }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devilbox-docker-php-fpm-personal:${{ matrix.versions }}
